/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javababushka_client_RedisClient */

#ifndef _Included_javababushka_client_RedisClient
#define _Included_javababushka_client_RedisClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javababushka_client_RedisClient
 * Method:    startSocketListenerExternal
 * Signature: (Ljavababushka/client/RedisClient;)V
 */
JNIEXPORT void JNICALL Java_javababushka_client_RedisClient_startSocketListenerExternal__Ljavababushka_client_RedisClient_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     javababushka_client_RedisClient
 * Method:    startSocketListenerExternal
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javababushka_client_RedisClient_startSocketListenerExternal__
  (JNIEnv *, jclass);

/*
 * Class:     javababushka_client_RedisClient
 * Method:    valueFromPointer
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_javababushka_client_RedisClient_valueFromPointer
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
