[package]
name = "babushka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "babushka"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
pyo3-asyncio = { version =  "0.16.0", features = ["tokio-runtime"] }
redis = { path = "../redis-rs", features = ["aio", "tokio-comp", "connection-manager"] }
tokio = { version = "^1", features = ["rt", "macros", "rt-multi-thread", "time"] }
