name: lint-ts
on:
    push:
        branches: ["main"]
        paths:
            - benchmarks/node/**
            - node/**
            - benchmarks/utilities/*
    pull_request:
        paths:
            - benchmarks/node/**
            - node/**
            - benchmarks/utilities/*

env:
    CARGO_TERM_COLOR: always
jobs:
    job:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - name: lint ts
              run: |
                  npm install @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-plugin-tsdoc eslint typescript
                  npm i
                  npx eslint .
